### ISSUE TITLE
Is it possible to use Graph Properties to generate better `.dot` files?

### ISSUE THREAD

**Issue by NoahStoryM** [stchang/graph#62]
For example, when generating `.dot` file, it will detect whether the vertex or edge has color attribute, and then draw graph based on the information.

By the way, will you consider adding `define-graph-property`? I think it can not only be used to better configure how to generate `.dot` files (For example, whether the edge is undirected, default color, etc.), but also provide some help to deal with different graphs.

**Comment by stchang** [comment]
I think you can already do the first using the `#:colors` parameter? Is that sufficient for your use case? It's true, however, that the `graphviz` function doesn't allow any other parameterization beyond colors at the moment, but I'm definitely open to suggestions.

For the second, how would `define-graph-property` specifically work? Would it essentially be an extension mechanism for the graph api? I think an implementation might be different for different use cases.
- Something like a `dot-graph` representation feels like it might be better implemented at the user level as a wrapper of one of the existing representations, with a few extra specific functions added? 
- Something like a `graph-type` could be added to the main api but that would again depend on the specific use case since we already have predicates like `weighted-graph?` and `unweighted-graph?` Do these not work for what you had in mind?

**Comment by NoahStoryM** [comment]
Hello, @stchang, I'm sorry I was busy the last two days, so I didn't notice your reply before.


> I think you can already do the first using the #:colors parameter? Is that sufficient for your use case?

I'm not sure if I missed something. In my understanding, graph-lib currently uses numbers to represent different colors. The number will be mapped to graphviz's triplet, but I'm not sure how to map numbers to the triplet I want (in a scene I hope to color nodes with gradient colors based on the distance of a root node). And the Dot language has a lot of configuration about colors, so I think maybe we can use `Property` to better compile graph into `.dot`.


> For the second, how would define-graph-property specifically work? Would it essentially be an extension mechanism for the graph api?

Regarding `define-graph-property`, I think `define-graph-property` can not only be used as a guide on how to generate `.dot`, it can also help us when dealing with different graphs. Although we already have predicates such as `weighted-graph?` to distinguish various types for graph, the types that can be distinguished only from the perspective of `edge` and `vertex`, which ignore the information of the graph itself.

I think a very typical example is the category theory. Graph is very suitable for describing the relation, so that it can be used as a language to express concepts in category theory. Graphs A B with the same vertices and the same edges may represent different categories and need to be treated differently.

I thought about implementing category-related api based on graph-lib. I thought maybe `define-graph-property` could be used to distinguish and process graphs with different meanings.


Speaking of it, I noticed that in the current graph-lib, the source and target can only have one edge:
```
> (require graph)
> (define g (unweighted-graph/directed'((a b) (a b))))
> (get-edges g)
'((a b))
```

Can we make graph-lib support multiple edges for them?

**Comment by stchang** [comment]
> In my understanding, graph-lib currently uses numbers to represent different colors

Yes, you're right, currently the number represents the "H" in the [graphviz HSV format](https://graphviz.org/docs/attr-types/color/). I'd be happy to make it more flexible to accommodate your needs though. Do you already have a fork that you could submit as a pr? Or if not could you give me some more specific test cases?

> very typical example is the category theory

Thanks for explaining your use case more. I think the best solution would be to implement a new representation, especially since I'm not sure how easily any of the existing implementations could be adapted to support multigraphs (https://github.com/stchang/graph/issues/57). What do you think? Again, I'd be happy to accept a pr if you already have something?

**Comment by NoahStoryM** [comment]
> I think the best solution would be to implement a new representation, especially since I'm not sure how easily any of the existing implementations could be adapted to support multigraphs (#57). What do you think? Again, I'd be happy to accept a pr if you already have something?


I don't have a deep understanding of the source code yet, and I am willing to try to make a fork after completing my current work.


> Or if not could you give me some more specific test cases?


This is an example of trying to customize colors under the current graph-lib: 
```
#lang racket

(require graph)

(define g (unweighted-graph/directed '((a a) (a b) (a c) (d a))))

(define my-colors (make-hash))
(for ([e (in-edges g)])
  (match-define `(,s ,t) e)
  (hash-update! my-colors t add1 (const 0)))

(pretty-display (graphviz g #:colors my-colors))
```

It will print the following (and I notice that `'(a a)` is undirected, which may be a BUG?):
```
digraph G {
	node0 [label="c",color="0.333 1.0 1.0"];
	node1 [label="a",color="0.666 1.0 1.0"];
	node2 [label="d"];
	node3 [label="b",color="0.333 1.0 1.0"];
	subgraph U {
		edge [dir=none];
		node1 -> node1;
	}
	subgraph D {
		node1 -> node0;
		node1 -> node3;
		node2 -> node1;
	}
}
```


I hope to use `properties` to generate `.dot` more flexible:
```
#lang racket

(require graph racket/undefined)

(define g (unweighted-graph/directed '((a a) (a b) (a c) (d a))) #:with-props 'graphviz)

;; Assume every vertex has properties like `graphviz/vertex-color`, `graphviz/vertex-label`, etc..
(for ([e (in-edges g)])
  (match-define `(,s ,t) e)
  (graphviz/vertex-set! t #:graph g #:key 'color #:value (hsv 0.5 1.0 1.0))
  (graphviz/vertex-set! s #:graph g #:key 'label #:value (format "source: ~a" s))
  (graphviz/vertex-set! t #:graph g #:key 'label #:value (format "target: ~a" t)))

;; Assume every edge has properties like `graphviz/edge-dir` etc..
(graphviz/edge-set! 'd 'a #:graph g #:key 'dir #:value 'none)

;; Assume that we have `graph-properties`.
(graphviz/graph-set! #:graph g #:key 'rankdir #:value 'LR)

;; Maybe we can add some parameters to custom some details:
(parameterize ([graphviz-indent "    "])
  (pretty-display (graphviz g)))

```

print the following:
```
digraph G {
    rankdir=LR;

    node0 [label="target: c",color="0.5 1.0 1.0"];
    node1 [label="target: a",color="0.5 1.0 1.0"];
    node2 [label="source: d"];
    node3 [label="target: b",color="0.5 1.0 1.0"];

    subgraph D {
        node1 -> node1;
        node1 -> node0;
        node1 -> node3;
        node2 -> node1 [dir=none];
    }
}

```

**Comment by stchang** [comment]
So the `graphviz` function has more or less been cobbled together by various users over the years for their needs. That's why it's a little ad-hoc.

The subgraphs were used so the `dir` for all the edges would only need to be declared once. But I agree there shouldnt ever be two subgraphs generated so you did find a bug

The problem is that the graph api currently doesnt support querying directedness ([but it's something we're trying to fix](https://github.com/stchang/graph/issues/64)) so `graphviz` has to infer it, with only partial success it seems.

I've pushed some changes that make your example work (See https://github.com/stchang/graph/commit/cff2803fc097c497dbd72019e40a1137b0bc0911). But since I'm not sure if it completely meets your needs, it's currently only in the `graphviz` branch.

I added your example as a test:

```racket
(define g (unweighted-graph/directed '((a a) (a b) (a c) (d a))))

(define targets '(a b c))
(define sources '(d))

(define-vertex-property g HSV-colors #:init (list 0.5 1.0 1.0))
(HSV-colors-set! 'd #f)

(define (mk-label v)
  (if (member v targets)
      (format "target: ~a" v)
      (format "source: ~a" v)))

(define-edge-property g dirs #:init #f)
(dirs-set! 'd 'a 'none)
(pretty-display (graphviz g
                          #:rankdir "LR"
                          #:mk-label mk-label
                          #:hsv-colors (HSV-colors->hash)
                          #:dirs (dirs->hash)
                          #:indent "    "))
```

produces:
```dot
digraph G {
    rankdir="LR";

    node0 [label="target: c",color="0.5 1.0 1.0"];
    node1 [label="target: a",color="0.5 1.0 1.0"];
    node2 [label="source: d"];
    node3 [label="target: b",color="0.5 1.0 1.0"];

    node1 -> node0;
    node1 -> node3;
    node1 -> node1;
    node2 -> node1 [dir=none];
}
```


Feel free to update it and submit a pr if you need more (or give me more examples).

The only thing is I would prefer if we only added functionality and didn't change existing behavior

**Comment by camoy** [comment]
I had the same desire, but want to use a different set of attributes. My proposed solution is #65, which doesn't fix the set of supported attributes. This does mean that the output can be an invalid Graphviz file (if you use a nonexistent or malformed attribute), but I think the added flexibility is worth that cost. There's [so many attributes](http://www.graphviz.org/doc/info/attrs.html). Enumerating them all, while "safer," probably isn't worth the complexity.

**Comment by stchang** [comment]
I believe https://github.com/stchang/graph/pull/65 addresses all the issues here? (re-open if it doesnt)
